SportComplexApp.Web/Areas/Admin/Controllers/FacilityManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportComplexApp.Services.Data.Contracts;
using SportComplexApp.Web.Controllers;
using SportComplexApp.Web.ViewModels.Facility;
using static SportComplexApp.Common.SuccessfulValidationMessages.Facility;
using static SportComplexApp.Common.ErrorMessages.Facility;

namespace SportComplexApp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class FacilityManagementController : BaseController
    {
        private readonly IFacilityService facilityService;

        public FacilityManagementController(IFacilityService facilityService)
        {
            this.facilityService = facilityService;
        }

        public async Task<IActionResult> All()
        {
            var facilities = await facilityService.GetAllAsync();
            return View(facilities);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new AddFacilityViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddFacilityViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (await facilityService.ExistsAsync(model.Name))
            {
                TempData["ErrorMessage"] = FacilityAlreadyExists;
                return View(model);
            }

            await facilityService.AddAsync(model);
            TempData["SuccessMessage"] = FacilityAdded;
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await facilityService.GetFacilityForEditAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AddFacilityViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await facilityService.EditAsync(id, model);
            TempData["SuccessMessage"] = FacilityUpdated;
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await facilityService.GetFacilityForDeleteAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await facilityService.DeleteAsync(id);
                TempData["SuccessMessage"] = FacilityDeleted;
            }
            catch (InvalidOperationException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }

            return RedirectToAction(nameof(All));
        }
    }
}

SportComplexApp.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SportComplexApp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SportComplexApp.Web/Areas/Admin/Controllers/SportManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportComplexApp.Services.Data.Contracts;
using SportComplexApp.Web.Controllers;
using SportComplexApp.Web.ViewModels.Sport;
using static SportComplexApp.Common.ErrorMessages.Sport;
using static SportComplexApp.Common.SuccessfulValidationMessages.Sport;

namespace SportComplexApp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SportManagementController : BaseController
    {
        private readonly ISportService sportService;

        public SportManagementController(ISportService sportService)
        {
            this.sportService = sportService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var sports = await sportService.GetAllSportsAsync();
            return View(sports);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = await sportService.GetAddFormModelAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddSportViewModel model)
        {
            if (model.MinPeople > model.MaxPeople)
            {
                ModelState.AddModelError(nameof(model.MaxPeople), MaxPeopleLessThanMin);
            }

            if (!ModelState.IsValid)
            {
                model.Facilities = await sportService.GetFacilitiesSelectListAsync();
                return View(model);
            }

            if (await sportService.ExistsAsync(model.Name))
            {
                TempData["ErrorMessage"] = SportAlreadyExists;
                model.Facilities = await sportService.GetFacilitiesSelectListAsync();
                return View(model);
            }

            await sportService.AddAsync(model);
            TempData["SuccessMessage"] = SportCreated;
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await sportService.GetSportForEditAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AddSportViewModel model)
        {
            if (model.MinPeople > model.MaxPeople)
            {
                ModelState.AddModelError(nameof(model.MaxPeople), MaxPeopleLessThanMin);
            }

            if (!ModelState.IsValid)
            {
                model.Facilities = await sportService.GetFacilitiesSelectListAsync();
                return View(model);
            }

            await sportService.EditAsync(id, model);
            TempData["SuccessMessage"] = SportUpdated;
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await sportService.GetSportForDeleteAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            await sportService.DeleteAsync(id);
            TempData["SuccessMessage"] = SportDeleted;
            return RedirectToAction(nameof(All));
        }
    }
}

SportComplexApp.Web/Areas/Admin/Controllers/TrainerManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportComplexApp.Services.Data.Contracts;
using SportComplexApp.Web.Controllers;
using SportComplexApp.Web.ViewModels.Trainer;
using static SportComplexApp.Common.ErrorMessages.Trainer;
using static SportComplexApp.Common.SuccessfulValidationMessages.Trainer;

namespace SportComplexApp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class TrainerManagementController : BaseController
    {
        private readonly ITrainerService trainerService;

        public TrainerManagementController(ITrainerService trainerService)
        {
            this.trainerService = trainerService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var trainers = await trainerService.GetAllAsync();
            return View(trainers);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new AddTrainerViewModel
            {
                AvailableSports = await trainerService.GetSportsAsSelectListAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTrainerViewModel model)
        {
            if(model.SelectedSportIds == null || !model.SelectedSportIds.Any())
            {
                ModelState.AddModelError(nameof(model.SelectedSportIds), MustSelectAtLeastOneSport);
            }

            if (!ModelState.IsValid)
            {
                model.AvailableSports = await trainerService.GetSportsAsSelectListAsync();
                return View(model);
            }

            await trainerService.AddAsync(model);
            TempData["SuccessMessage"] = TrainerAdded;
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await trainerService.GetTrainerForEditAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            model.AvailableSports = await trainerService.GetSportsAsSelectListAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AddTrainerViewModel model)
        {
            if (model.SelectedSportIds == null || !model.SelectedSportIds.Any())
            {
                ModelState.AddModelError(nameof(model.SelectedSportIds), MustSelectAtLeastOneSport);
            }

            if (!ModelState.IsValid)
            {
                model.AvailableSports = await trainerService.GetSportsAsSelectListAsync();
                return View(model);
            }

            await trainerService.EditAsync(id, model);
            TempData["SuccessMessage"] = TrainerUpdated;
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var trainer = await trainerService.GetTrainerForDeleteAsync(id);
            if (trainer == null)
            {
                return NotFound();
            }

            return View(trainer);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            await trainerService.DeleteAsync(id);
            TempData["SuccessMessage"] = TrainerDeleted;
            return RedirectToAction(nameof(All));
        }
    }
}

SportComplexApp.Web/Areas/Admin/Controllers/UserManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SportComplexApp.Data.Models;
using SportComplexApp.Services.Data.Contracts;
using SportComplexApp.Web.Controllers;
using static SportComplexApp.Common.ErrorMessages.Users;
using static SportComplexApp.Common.SuccessfulValidationMessages.Users;

namespace SportComplexApp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserManagementController : BaseController
    {
        private readonly IUserService userService;
        private readonly UserManager<Client> userManager;

        public UserManagementController(IUserService userService, UserManager<Client> userManager)
        {
            this.userService = userService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var allUsers = await userService.GetAllUsersAsync();
            return View(allUsers);
        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(string userId, string role)
        {
            if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(role))
            {
                TempData["ErrorMessage"] = UserIdOrRoleCannotBeEmpty;
                return RedirectToAction(nameof(Index));
            }

            bool userExists = await userService.UserExistsByIdAsync(userId);

            if (!userExists)
            {
                return NotFound();
            }

            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                TempData["ErrorMessage"] = UserDoesNotExist;
                return RedirectToAction(nameof(Index));
            }

            if (await userManager.IsInRoleAsync(user, role))
            {
                TempData["ErrorMessage"] = UserAlreadyInRole;
                return RedirectToAction(nameof(Index));
            }

            bool assignResult = await userService.AssignUserToRoleAsync(userId, role);

            if (!assignResult)
            {
                TempData["ErrorMessage"] = FailedToAssignRole;
                return RedirectToAction(nameof(Index));
            }

            TempData["SuccessMessage"] = RoleAssigned;
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveRole(string userId, string role)
        {
            if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(role))
            {
                TempData["ErrorMessage"] = UserIdOrRoleCannotBeEmpty;
                return RedirectToAction(nameof(Index));
            }

            bool userExists = await userService.UserExistsByIdAsync(userId);

            if (!userExists)
            {
                return NotFound();
            }

            bool removeRoleResult = await userService.RemoveUserRoleAsync(userId, role);

            if (!removeRoleResult)
            {
                TempData["ErrorMessage"] = FailedToRemoveRole;
                return RedirectToAction(nameof(Index));
            }

            TempData["SuccessMessage"] = RoleRemoved;
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                TempData["ErrorMessage"] = UserIdOrRoleCannotBeEmpty;
                return RedirectToAction(nameof(Index));
            }

            bool userExists = await userService.UserExistsByIdAsync(userId);

            if (!userExists)
            {
                return NotFound();
            }

            bool deleteResult = await userService.DeleteUserAsync(userId);

            if (!deleteResult)
            {
                TempData["ErrorMessage"] = FailedToDeleteUser;
                return RedirectToAction(nameof(Index));
            }

            TempData["SuccessMessage"] = UserDeleted;
            return RedirectToAction(nameof(Index));
        }
    }
}

SportComplexApp.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SportComplexApp.Services.Data.Contracts;
using SportComplexApp.Web.ViewModels.Home;

namespace SportComplexApp.Web.Controllers;

public class HomeController : Controller
{
    private readonly ISportService sportService;
    private readonly ITrainerService trainerService;
    private readonly ISpaService spaService;
    public HomeController(ISportService sportService, ITrainerService trainerService, ISpaService spaService)
    {
        this.sportService = sportService;
        this.trainerService = trainerService;
        this.spaService = spaService;
    }

    public async Task<IActionResult> Index()
    {
        var model = new HomePageViewModel
        {
            Sports = await sportService.GetAllForHomeAsync(),
            Trainers = await trainerService.GetAllForHomeAsync(),
            SpaProcedures = await spaService.GetAllForHomeAsync()
        };

        return View(model);
    }

    public IActionResult Error(int? statusCode = null)
    {
        if (statusCode == 404)
        {
            return View("Error404");
        }

        return View("Error500");
    }
}

SportComplexApp.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Admin Dashboard";
}

<div class="admin-hero rounded-4 p-4 p-md-5 mb-5">
    <div class="d-flex align-items-center gap-3">
        <div class="hero-icon d-flex align-items-center justify-content-center rounded-3">
            <i class="bi bi-speedometer2"></i>
        </div>
        <div>
            <h1 class="h3 mb-1 text-white">Admin Panel</h1>
            <p class="mb-0 text-white-50">Manage users, trainers, sports, facilities, spa services & tournaments</p>
        </div>
    </div>
</div>

<div class="row g-4">
    @* Users *@
    <div class="col-12 col-md-6 col-xl-4">
        <a asp-area="Admin" asp-controller="UserManagement" asp-action="Index" class="text-decoration-none">
            <div class="card admin-card h-100">
                <div class="card-body p-4 d-flex flex-column justify-content-between">
                    <div class="d-flex align-items-start gap-3">
                        <div class="pill-icon">
                            <i class="bi bi-people-fill"></i>
                        </div>
                        <div>
                            <h3 class="h5 text-white mb-1">Manage Users</h3>
                            <p class="mb-0 text-white-50 small">Create, edit, deactivate accounts</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>

    @* Trainers *@
    <div class="col-12 col-md-6 col-xl-4">
        <a asp-area="Admin" asp-controller="TrainerManagement" asp-action="All" class="text-decoration-none">
            <div class="card admin-card h-100">
                <div class="card-body p-4 d-flex flex-column justify-content-between">
                    <div class="d-flex align-items-start gap-3">
                        <div class="pill-icon">
                            <i class="bi bi-person-badge-fill"></i>
                        </div>
                        <div>
                            <h3 class="h5 text-white mb-1">Manage Trainers</h3>
                            <p class="mb-0 text-white-50 small">Profiles, schedules, approvals</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>

    @* Sports *@
    <div class="col-12 col-md-6 col-xl-4">
        <a asp-area="Admin" asp-controller="SportManagement" asp-action="All" class="text-decoration-none">
            <div class="card admin-card h-100">
                <div class="card-body p-4 d-flex flex-column justify-content-between">
                    <div class="d-flex align-items-start gap-3">
                        <div class="pill-icon">
                            <i class="bi bi-basket2-fill"></i>
                        </div>
                        <div>
                            <h3 class="h5 text-white mb-1">Manage Sports</h3>
                            <p class="mb-0 text-white-50 small">Categories, levels, pricing</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>

    @* Facilities *@
    <div class="col-12 col-md-6 col-xl-4">
        <a asp-area="Admin" asp-controller="FacilityManagement" asp-action="All" class="text-decoration-none">
            <div class="card admin-card h-100">
                <div class="card-body p-4 d-flex flex-column justify-content-between">
                    <div class="d-flex align-items-start gap-3">
                        <div class="pill-icon">
                            <i class="bi bi-building"></i>
                        </div>
                        <div>
                            <h3 class="h5 text-white mb-1">Manage Facilities</h3>
                            <p class="mb-0 text-white-50 small">Courts, rooms, availability</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>

    @* Spa *@
    <div class="col-12 col-md-6 col-xl-4">
        <a asp-area="Admin" asp-controller="SpaServicesManagement" asp-action="All" class="text-decoration-none">
            <div class="card admin-card h-100">
                <div class="card-body p-4 d-flex flex-column justify-content-between">
                    <div class="d-flex align-items-start gap-3">
                        <div class="pill-icon">
                            <i class="bi bi-flower3"></i>
                        </div>
                        <div>
                            <h3 class="h5 text-white mb-1">Manage Spa Services</h3>
                            <p class="mb-0 text-white-50 small">Treatments, durations, staff</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>

    @* Tournaments *@
    <div class="col-12 col-md-6 col-xl-4">
        <a asp-area="Admin" asp-controller="TournamentManagement" asp-action="All" class="text-decoration-none">
            <div class="card admin-card h-100">
                <div class="card-body p-4 d-flex flex-column justify-content-between">
                    <div class="d-flex align-items-start gap-3">
                        <div class="pill-icon">
                            <i class="bi bi-trophy-fill"></i>
                        </div>
                        <div>
                            <h3 class="h5 text-white mb-1">Manage Tournaments</h3>
                            <p class="mb-0 text-white-50 small">Brackets, dates, registrations</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>

@section Scripts {
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <style>
        .admin-hero {
            background: linear-gradient(135deg, #121212, #1a1a1a);
            border: 1px solid rgba(255,255,255,.06);
        }

        .hero-icon {
            width: 60px;
            height: 60px;
            background: #1f1f1f;
            color: #fff;
            font-size: 1.5rem;
            border: 1px solid rgba(255,255,255,.08);
        }

        .admin-card {
            background: #171717;
            border: 1px solid rgba(255,255,255,.06);
            border-radius: 1rem;
            transition: transform .18s ease, box-shadow .18s ease, border-color .18s ease;
        }

            .admin-card:hover {
                transform: translateY(-3px);
                box-shadow: 0 .9rem 1.6rem rgba(0,0,0,.35);
                border-color: rgba(0,255,200,.25);
            }

        .pill-icon {
            width: 48px;
            height: 48px;
            border-radius: 12px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            background: #1f1f1f;
            color: #e6e6e6;
            border: 1px solid rgba(255,255,255,.08);
            font-size: 1.25rem;
        }

        .admin-card:hover .pill-icon {
            border-color: rgba(0,255,200,.35);
            color: #00ffc8;
        }
    </style>
}